### ISSUE TITLE
 TheHiveDocs/installation/docker-guide.md

### ISSUE THREAD

**Issue by remg427** [CERT-BDF/TheHiveDocs#10]
in the docker-compose.yml shouldn't be 
 cortex:
    image: certbdf/cortex:latest
    ports:
      - "0.0.0.0:9001:900**1**"

**Comment by To-om** [comment]
Cortex listens on 9000/tcp port by default (like TheHive). The port 9000/tcp (inside the container) will be exposed to port 9001/tcp (in host). So this configuration is ok: --publish 0.0.0.0:9001:9000.
