### ISSUE TITLE
Elasticsearch to current version?

### ISSUE THREAD

**Issue by techgourmet** [CERT-BDF/TheHiveDocs#7]
Hi,

I see that you are still using Elasticsearch 2 within thehive.
Can you please update compatibility to Elasticsearch 5.x which is the current version?

Thanks in advance.

**Comment by saadkadhi** [comment]
Hello. Issues pertaining to TheHive (except its documentation) must be opened in the [corresponding repository](https://github.com/CERT-BDF/TheHive/issues). 

Using ES 5 is already planned for Mellifera 13 (2.13.0), which should be released in September. Thus I am going to close this request.

**Comment by techgourmet** [comment]
Thanks for the info.
You can keep the issue closed
