### ISSUE TITLE
Typo in install steps - 'yum install install' (https://github.com/CERT-BDF/TheHiveDocs/blob/master/installation/rpm-guide.md)

### ISSUE THREAD

**Issue by simonsigre** [CERT-BDF/TheHiveDocs#9]
Just as an FYI the RPM install guide (https://github.com/CERT-BDF/TheHiveDocs/blob/master/installation/rpm-guide.md)  has the following line
```
yum install install https://dl.bintray.com/cert-bdf/rpm/thehive-project-release-1.0.0-3.noarch.rpm
```
install install ?

**Comment by nadouani** [comment]
Hello, this is a typo, I'll fix it. Thanks
